import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { StoreProvider } from "./StoreProvider";
import { Box, ThemeProvider } from "@mui/material";
import Navbar from "./components/Navbar";
import { theme } from "./theme";
import Loader from "./components/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <ThemeProvider theme={theme}>
        <html lang="en">
          <body className={inter.className}>
            <Navbar />
            <Loader />
            <Box sx={{ mt: "110px" }}>{children}</Box>
          </body>
        </html>
      </ThemeProvider>
    </StoreProvider>
  );
}
